# Generated by Django 4.1.3 on 2022-11-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='username',
            field=models.CharField(max_length=50, verbose_name='نام کاربری'),
        ),
    ]
